# Generated by Django 3.1.5 on 2021-11-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotStatus',
            fields=[
                ('device_id', models.TextField(max_length=200, primary_key=True, serialize=False)),
                ('slot_1', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('slot_2', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
            ],
        ),
    ]
